[feature] ISSUE05 이슈 생성시 history 추가
Comento-Hyune-c/issuetracker-01-02 pull request #11
Opened 2022-11-08 14:07 UTC by seonyeongLee

2022-11-08 14:11 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
> +                .issueInfo(issue.getIssueDesc()).build());
이전 리뷰에서 다음과 같이 피드백을 주신 부분에 대해서 추가적으로 궁금한 부분에 대해서 질문 드립니다!
```
builder 패턴은 상당한 인적 오류의 위험성을 가지고 있습니다.
개인적으로는 prod 코드에서 사용하지 않으며, 아주 보수적으로 생성자에서만 사용하곤 합니다.
```
만약, builder 패턴을 사용하지 않으면 각각 set을 해야한다고 생각합니다. 이렇게 될 경우 코드를 읽기가 더 어렵다고 생각이 드는데 혹시 더 좋은 방법이 있을까요??

2022-11-09 03:07 UTC, Hyune-c requested changes
수고하셨습니다.

2022-11-09 03:07 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
> +                .issueInfo(issue.getIssueDesc()).build());
저는 목적에 맞는 생성자를 만드는 것을 추천합니다.
생성자 오버로딩도 좋고 정적 팩토리 메소드도 좋습니다.

---

- 객체 생성시 builder 활용
- 객체에 필드가 추가됨
- builder 사용하는 곳이 너무 많다보니 빼먹은 곳이 있음.
    - 해당 필드가 null 되어버림

개인적으로 경험했었던 문제는 위와 같습니다.
추가로 아래 글을 읽어보시면 좋을 것 같습니다.

https://tecoble.techcourse.co.kr/post/2020-08-17-builder_pattern/

2022-11-09 03:07 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
>  }
<img width="694" alt="image" src="https://user-images.githubusercontent.com/55722186/200727907-73d2d1bf-9a34-4c6c-aac9-e15fd74f4e3f.png">

eof 가 계속 보이네요.
위 설정을 추천합니다. 이후 eof 에 대해서는 코멘트하지 않겠습니다.

2022-11-09 03:07 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/converter/IssueTypeConverter.java
> +public class IssueTypeConverter implements AttributeConverter<IssueType, String> {
`nit` 혹시 `@Converter` 없이도 정상 작동 되나요?

2022-11-09 03:07 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/constant/IssueType.java
> +    }
`nit` lombok 의 도움을 받을 수 있을 것 같습니다.

2022-11-09 03:07 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/constant/IssueType.java
> +    DEVELOPMENT("DEVELOPMENT");
이것은 history type 일까요 issue type 일까요?

2022-11-09 08:28 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/constant/IssueType.java
> +    DEVELOPMENT("DEVELOPMENT");
이슈 히스토리에 대한 부분이여서 IssueHistoryType이 조금 더 적절할 것 같다는 생각이 들어요!

2022-11-09 08:29 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/converter/IssueTypeConverter.java
> +public class IssueTypeConverter implements AttributeConverter<IssueType, String> {
네, '@Converter' 없이도 정상 작동 합니다!

2022-11-09 08:51 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
> +                .issueInfo(issue.getIssueDesc()).build());
해당 부분에 대해서 필드가 추가될 경우 문제가 발생할 가능성이 높을 것 같다고 생각이 되서 정적 팩토리 메소드 사용으로 변경해보았습니다!

2022-11-09 14:29 UTC, Hyune-c approved these changes

2022-11-09 14:29 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
> +}
`@Transactional` 을 걸지 않으신 이유가 있을까요?

2022-11-09 14:29 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/entity/IssueHistory.java
> +    private String issueHistoryInfo;
`nit` info 라는 표현은 모호하다는 의견도 있습니다.
하지만 충분히 고민 후 info 가 적절하다면 쓰는 것도 방법이라고 생각합니다.

https://sheerheart.tistory.com/entry/%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-2%EC%9E%A5-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84-%EC%9A%94%EC%95%BD

2022-11-09 14:29 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issueHistory/entity/IssueHistory.java
> +    }
`nit` 개인적으로는 생성자 한정으로 builder 를 사용하기도 합니다.
이전 리뷰에서 반대하였던 이유는 prod 코드에 산발적으로 퍼질 수 있다는 위험이 있어서였습니다.
하지만 지금처럼 생성자나 factory 등으로 응집될 수 있다면 휴먼 에러의 포인트가 충분히 줄어들 수 있다고 생각합니다.

이것은 딱히 정답이 없습니다. 어느정도는 취향 차이인 것 같기도 합니다.

2022-11-10 15:00 UTC, merged