[feature] ISSUE01 이슈 생성
Comento-Hyune-c/issuetracker-01-02 pull request #7
Opened 2022-11-02 09:30 UTC by seonyeongLee

이슈 생성

2022-11-02 13:30 UTC, Hyune-c requested changes
`nit` 중요하지는 않지만 더 나은 방법이 있다는 의견을 남기고 싶을 때 사용한다.

---

전체적으로 조금 더 간결한 코드로 개선할 수 있다고 생각합니다.
수정 PR 을 기다리겠습니다~

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +    String statusMessage;
```suggestion
    final int statusCode;
    final String statusMessage;
```

`nit ` final 사용을 권장합니다.
`nit` Getter 는 클래스 레벨에 붙이는 것이 더 좋다고 생각합니다.
`nit` 생성wk eotls `@AllArgsConstructor` 을 활용할 수 있을 것 같아요.

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +}
eof 처리해주세요!

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +    NOT_FOUND(404, "NOT_FOUND"),
```suggestion
    // import org.springframework.http.HttpStatus;
    NOT_FOUND(HttpStatus.NOT_FOUND.value(), HttpStatus.NOT_FOUND.name()),
```
`nit` Spring 을 활용한다면 이런 방법도 있습니다.

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/repository/IssueReposistory.java
> +public interface IssueReposistory extends JpaRepository<Issue, Long> {
```suggestion
public interface IssueRepository extends JpaRepository<Issue, Long> {
```

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/entity/Issue.java
> +@DynamicUpdate
DynamicUpdate 는 단점이 있습니다. 
혹시 설명해주실 수 있을까요?

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/entity/Issue.java
> +    }
request 는 web 레이어의 객체입니다.
영속성 레이어의 객체가 web 레이어의 객체를 안다는 것에 대해 어떻게 생각하시나요?

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/service/IssueService.java
> +        return issueReposistory.save(issue).getIssueId();
👍

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +        return ResponseEntity.ok(new ErrorResponse(CreateIssueResponse.builder().issueId(issueId).build()));
`@RestController` 를 사용하면서 `ResponseEntity` 로 반환형을 사용하는 것에 대해 어떻게 생각하시나요?

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +        Long issueId = issueService.createIssue(new Issue(request));
`new Issue(request)` 
영속성 객체를 web 레이어에서 알고 있다는 것에 대해 어떻게 생각하시나요?

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +    public ResponseEntity<ErrorResponse> createIssue(@RequestBody @Valid CreateIssueRequest request) {
`ErrorResponse` 가 맞나요?
이 메서드 호출의 결과는 200 ok 를 기대하는 것으로 보입니다

2022-11-02 13:30 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/request/CreateIssueRequest.java
> +public class CreateIssueRequest {
`nit` `@Data` 또는 record 자룔형을 쓰는 것도 방법입니다.
`nit` CreateIssueRequest 와 IssueCreateRequest 중 어떤 것이 더 좋아보이시나요?

2022-11-03 15:13 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/request/CreateIssueRequest.java
> +public class CreateIssueRequest {
@Hyune-c `@Data`의 경우에 원하지 않는 annotation도 포함될 수 있어서 지양한다고 알고 있는데 멘토님은 이에 대해서 어떻게 생각하실까요??

2022-11-03 15:18 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +    String statusMessage;
@Getter 를 클래스 레벨에 붙일때 얻을 수 있는 이점이 있는지 궁금합니다!

2022-11-03 20:19 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +    String statusMessage;
- LOC (line of code) 가 줄어듭니다.
- lombok 을 보수적으로 쓰라는 얘기가 많긴 하지만 개인적으로 getter 는 클래스 레벨에서 열어줘도 좋다고 생각 합니다.

---

![image](https://user-images.githubusercontent.com/55722186/199824214-0dd90acc-0634-4add-8fad-0bbcb093ac7a.png)
- `@` 를 사용하는 경우는 꼭 별도 처리를 해주세요. 엄한 계정이 태그 됩니다.

2022-11-03 20:19 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/domain/issue/entity/Issue.java
> +@DynamicUpdate
jpa 는 update 쿼리를 캐시하여 사용하기에 성능상 이점이 있습니다.
하지만 그렇다고 해서 DynamicUpdate 를 사용하지 말라는 뜻은 아닙니다.
필요에 따라서는 사용해야 합니다.

https://jojoldu.tistory.com/415
https://hyune-c.tistory.com/entry/DynamicUpdate-%ED%99%9C%EC%9A%A9%EA%B8%B0

2022-11-03 20:19 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/request/CreateIssueRequest.java
> +public class CreateIssueRequest {
네. 보통 `Data` 의 단점으로 불필요한 annotation 의 추가를 말하곤 합니다.
하지만 java 14 에서 처음 등장한 record 나 kotlin 의 data 클래스를 보면 조금 방향이 다릅니다.

개인적으로는 dto 에 한해서 `Data` 를 사용해도 좋다고 생각합니다.

2022-11-04 09:01 UTC, Hyune-c approved these changes
이전에 코멘트한 내용에 대해서는 추가 코멘트하지 않습니다.
수고하셨습니다.

2022-11-04 09:01 UTC, Hyune-c commented on issuetracker-api/src/main/java/com/comento/issuetracker/exception/ExceptionController.java
> +        log.info("MethodArgumentNotValidException => {}", exception.getBindingResult());
👍

2022-11-07 09:56 UTC, merged

2022-11-07 10:39 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +        return ResponseEntity.ok(new ErrorResponse(CreateIssueResponse.builder().issueId(issueId).build()));
RestController를 사용함에 따라서 ResponseEntity에 해당하는 형태를 따라야 한다고 생각합니다.

2022-11-07 10:40 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +        Long issueId = issueService.createIssue(new Issue(request));
영속성 객체를 web레이어에서 모르는게 더 격리가 잘되었다고 판단이되서 해당 부분 아래와 같이 수정했습니다.
```
Issue issue = Issue.builder()
            .issueTitle(request.getIssueTitle())
            .issueDesc(request.getIssueDesc())
            .build();
```

2022-11-07 10:40 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +    public ResponseEntity<ErrorResponse> createIssue(@RequestBody @Valid CreateIssueRequest request) {
200 ok에 error는 올바르지 않았던 것 같습니다..ㅜㅜ

2022-11-07 10:41 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/constant/HttpStatusEnum.java
> +    INTERNAL_SERER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR.value(), HttpStatus.INTERNAL_SERVER_ERROR.name());
HttpStatus를 import로 올려서 사용하니 동일한 네이밍(?) 으로 인해서 오류가 발생해서 HttpStatusEnum은 삭제처리 후 HttpStatus를 사용했습니다.
* 오류 발생 코드 예시
BAD_REQUEST(BAD_REQUEST.value(),BAD_REQUEST.name()),

2022-11-07 10:42 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/web/IssueController.java
> +            .build();
만약, builder 패턴을 사용하지 않으면 각각 set을 해야한다고 생각합니다. 이렇게 될 경우 코드를 읽기가 더 어렵다고 생각이 드는데 혹시 더 좋은 방법이 있을까요??

2022-11-07 10:45 UTC, seonyeongLee commented on issuetracker-api/src/main/java/com/comento/issuetracker/exception/ExceptionController.java
> +            .code(HttpStatusEnum.BAD_REQUEST.getStatusCode())
annotation에 대해서 확인해보았을때 다음과 같이 사용하는걸 확인했습니다. '@ResponseStatus(HttpStatus.BAD_REQUEST)'
이 경우에 제가 원하는 메세지 문구는 어떻게 내려주는 방법은 없는 것 같습니다.. 이 경우에는 멘토님께서 말씀해주신 에러처럼 bindingResult를 전체적으로 내려주는 방식으로 해결해야 될까요?

2022-11-07 10:46 UTC, seonyeongLee commented
@Hyune-c 소영님께서 개발하실수 있도록 merge를 먼저 진행하였습니다. 추가적으로 궁금한 부분에 대해서 답글을 달아서 확인 부탁드립니다!